services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: thrifting_buddy_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: thriftingbuddy
      POSTGRES_PASSWORD: dev_password_123
      POSTGRES_DB: thrifting_buddy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thriftingbuddy"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: thrifting_buddy_redis
    restart: unless-stopped
    command: redis-server --requirepass redis_dev_123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_dev_123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    image: thrifting-buddy/backend:latest
    container_name: thrifting_buddy_api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ./backend/.env
    environment:
      # Override DATABASE_URL and REDIS_URL to use container networking
      DATABASE_URL: postgresql://thriftingbuddy:dev_password_123@postgres:5432/thrifting_buddy
      REDIS_URL: redis://:redis_dev_123@redis:6379
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Web Application
  frontend:
    build:
      context: ./mobile-app
      dockerfile: Dockerfile.frontend
    image: thrifting-buddy/frontend:latest
    container_name: thrifting_buddy_frontend
    restart: unless-stopped
    # No external ports - accessed via nginx proxy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Nginx Reverse Proxy (containerized with config)
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: thrifting-buddy/nginx:latest
    container_name: thrifting_buddy_nginx
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Mobile App Web Server (production containerized)
  mobile-web:
    build:
      context: ./mobile-app
      dockerfile: Dockerfile.mobile-web
    image: thrifting-buddy/mobile-web:latest
    container_name: thrifting_buddy_mobile_web
    restart: unless-stopped
    ports:
      - "19006:19006"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19006/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: thrifting_buddy_network