version: '3.8'

services:
  # Backend API (simplified)
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.backend
    image: thrifting-buddy/backend:latest
    container_name: thrifting_buddy_api
    restart: unless-stopped
    env_file:
      - ../backend/.env
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend (simplified)
  frontend:
    build:
      context: ../mobile-app
      dockerfile: Dockerfile.frontend-node
    image: thrifting-buddy/frontend:latest
    container_name: thrifting_buddy_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:8080"
    environment:
      REACT_APP_API_URL: http://localhost:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: thrifting_buddy_network