services:
  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: thrifting_buddy_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - backend
      - frontend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  # Certbot for Let's Encrypt
  certbot:
    image: certbot/certbot:latest
    container_name: thrifting_buddy_certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # Backend API
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.backend
    image: thrifting-buddy/backend:v0.1.1
    container_name: thrifting_buddy_api
    restart: unless-stopped
    env_file:
      - ../backend/.env
    expose:
      - "3000"

  # Frontend
  frontend:
    build:
      context: ../mobile-app
      dockerfile: Dockerfile.frontend-node
    image: thrifting-buddy/frontend:v0.1.1
    container_name: thrifting_buddy_frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: https://app.flippi.ai
    expose:
      - "8080"

networks:
  default:
    name: thrifting_buddy_network