version: '3'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: thrifting-buddy/backend:v0.1.1
    container_name: prod_backend
    restart: unless-stopped
    env_file:
      - ../../../shared/.env
    networks:
      - prod_network
      - proxy_network
    environment:
      - VIRTUAL_HOST=app.flippi.ai
      - VIRTUAL_PATH=/api,/health
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=app.flippi.ai
      - LETSENCRYPT_EMAIL=admin@flippi.ai

  frontend:
    build:
      context: ../mobile-app
      dockerfile: Dockerfile
    image: thrifting-buddy/frontend:v0.1.1
    container_name: prod_frontend
    restart: unless-stopped
    networks:
      - prod_network
      - proxy_network
    environment:
      - VIRTUAL_HOST=app.flippi.ai
      - VIRTUAL_PATH=/
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=app.flippi.ai
      - LETSENCRYPT_EMAIL=admin@flippi.ai

networks:
  prod_network:
    name: prod_network
  proxy_network:
    external: true
