#!/bin/bash

# This script provides the SSH commands to run on the server to fix the legal pages

echo "Run these commands on the server (SSH into 157.245.142.145):"
echo ""
echo "# 1. Update blue.flippi.ai nginx config"
echo "sudo nano /etc/nginx/sites-available/blue.flippi.ai"
echo ""
echo "# Find these lines:"
echo "#    location /privacy {"
echo "#        alias /var/www/blue.flippi.ai/mobile-app/privacy.html;"
echo "#        try_files \$uri =404;"
echo "#    }"
echo ""
echo "# Change to:"
echo "#    location = /privacy {"
echo "#        alias /var/www/blue.flippi.ai/mobile-app/privacy.html;"
echo "#    }"
echo ""
echo "#    location = /terms {"
echo "#        alias /var/www/blue.flippi.ai/mobile-app/terms.html;"
echo "#    }"
echo ""
echo "# 2. Test and reload nginx"
echo "sudo nginx -t && sudo nginx -s reload"
echo ""
echo "# 3. Verify the pages work"
echo "curl -I https://blue.flippi.ai/privacy"
echo "curl -I https://blue.flippi.ai/terms"