#!/bin/bash
# Quick fix to add legal pages routes after deployment

echo "Adding legal pages proxy routes to nginx..."
echo ""
echo "MANUAL STEPS REQUIRED:"
echo "1. SSH into the server"
echo "2. Edit /etc/nginx/sites-available/blue.flippi.ai"
echo "3. Add these location blocks BEFORE the 'location /' block:"
echo ""
echo "    location = /terms {"
echo "        proxy_pass http://localhost:3002;"
echo "        proxy_http_version 1.1;"
echo "        proxy_set_header Host \$host;"
echo "        proxy_set_header X-Real-IP \$remote_addr;"
echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
echo "        proxy_set_header X-Forwarded-Proto \$scheme;"
echo "    }"
echo ""
echo "    location = /privacy {"
echo "        proxy_pass http://localhost:3002;"
echo "        proxy_http_version 1.1;"
echo "        proxy_set_header Host \$host;"
echo "        proxy_set_header X-Real-IP \$remote_addr;"
echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
echo "        proxy_set_header X-Forwarded-Proto \$scheme;"
echo "    }"
echo ""
echo "4. Test with: sudo nginx -t"
echo "5. Reload with: sudo systemctl reload nginx"