name: Check Production Environment
on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check production environment setup
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 157.245.142.145
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "=== Checking Production Environment ==="
            echo "NOTE: This is READ-ONLY access per CLAUDE.md"
            
            # Check if shared .env exists
            echo "1. Checking shared .env location:"
            ls -la /var/www/shared/.env 2>/dev/null || echo "No shared .env"
            
            # Check production backend .env (without showing the key)
            echo ""
            echo "2. Checking if production has API key configured:"
            if [ -f /var/www/app.flippi.ai/backend/.env ]; then
              grep -q "OPENAI_API_KEY=sk-proj" /var/www/app.flippi.ai/backend/.env && echo "✓ Production has OpenAI API key" || echo "✗ No API key found"
            fi
            
            # Check if there's a pattern we can use
            echo ""
            echo "3. API key pattern check:"
            grep "OPENAI_API_KEY" /var/www/app.flippi.ai/backend/.env | sed 's/=.*/=***HIDDEN***/'
            
            echo ""
            echo "=== End Check ==="