name: Deploy Production
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to app.flippi.ai
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 157.245.142.145
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/app.flippi.ai
            # Fix git ownership issue
            git config --global --add safe.directory /var/www/app.flippi.ai
            # Reset any local changes to avoid merge conflicts
            git reset --hard HEAD
            git clean -fd
            # Force update to match remote exactly
            git fetch origin master
            git reset --hard origin/master
            
            # Export build metadata for version endpoint
            export BUILD_VERSION="release-005"
            export COMMIT_SHA=$(git rev-parse --short HEAD)
            export BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            
            # Write build metadata to .env file
            echo "" >> backend/.env
            echo "# Build metadata" >> backend/.env
            echo "BUILD_VERSION=$BUILD_VERSION" >> backend/.env
            echo "COMMIT_SHA=$COMMIT_SHA" >> backend/.env
            echo "BUILD_TIME=$BUILD_TIME" >> backend/.env
            
            cd backend && npm install --production
            
            # Build frontend (no timeout, like staging workflow)
            cd ../mobile-app && npm install && npx expo export --platform web --output-dir dist
            
            # Restart PM2 services
            pm2 restart prod-backend prod-frontend
            # Wait for services to start
            sleep 3
            # Check if backend is running
            pm2 show prod-backend || true
            curl -s http://localhost:3000/health || echo "Backend not responding"
            
            # Clear nginx cache
            sudo rm -rf /var/cache/nginx/*
            sudo nginx -s reload
            
            # Run post-deploy fixes for growth routes
            echo "=== Ensuring growth routes are configured ==="
            if [ -f scripts/fix-growth-routes.sh ]; then
              sudo bash scripts/fix-growth-routes.sh
            fi
            
            # Post-deployment verification
            echo "=== Post-Deployment Verification ==="
            echo "Git commit: $(git rev-parse HEAD)"
            echo "Build version: $BUILD_VERSION"
            echo "Build time: $BUILD_TIME"
            
            # Check version endpoint
            sleep 5  # Give services time to fully start
            echo "Version endpoint check:"
            curl -s http://localhost:3000/api/version | jq . || echo "Version endpoint not responding"
            
            # Run nginx cache clear script if available
            if [ -f scripts/clear-nginx-cache.sh ]; then
              bash scripts/clear-nginx-cache.sh prod
            fi