name: Deploy Nginx Templates

on:
  workflow_dispatch:
  push:
    paths:
      - 'nginx-templates/**'
    branches:
      - develop
      - staging
      - master

jobs:
  deploy-nginx:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy Nginx Templates
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 157.245.142.145
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "=== Deploying Nginx Templates ==="
          
          # Create temp directory
          TEMP_DIR="/tmp/nginx-deploy-$(date +%s)"
          mkdir -p $TEMP_DIR
          
          # Clone the repository to get the templates
          cd $TEMP_DIR
          git clone https://github.com/johnjhusband/price-scanner-app.git
          cd price-scanner-app
          
          # Check which branch we're on
          BRANCH="${{ github.ref_name }}"
          git checkout $BRANCH
          
          # Backup existing configs
          echo "Backing up existing configs..."
          [ -f /etc/nginx/sites-available/blue.flippi.ai ] && cp /etc/nginx/sites-available/blue.flippi.ai /etc/nginx/sites-available/blue.flippi.ai.backup-$(date +%Y%m%d-%H%M%S)
          [ -f /etc/nginx/sites-available/green.flippi.ai ] && cp /etc/nginx/sites-available/green.flippi.ai /etc/nginx/sites-available/green.flippi.ai.backup-$(date +%Y%m%d-%H%M%S)
          [ -f /etc/nginx/sites-available/app.flippi.ai ] && cp /etc/nginx/sites-available/app.flippi.ai /etc/nginx/sites-available/app.flippi.ai.backup-$(date +%Y%m%d-%H%M%S)
          
          # Copy new templates
          echo "Copying new templates..."
          cp nginx-templates/blue.flippi.ai.conf /etc/nginx/sites-available/blue.flippi.ai
          cp nginx-templates/green.flippi.ai.conf /etc/nginx/sites-available/green.flippi.ai
          cp nginx-templates/app.flippi.ai.conf /etc/nginx/sites-available/app.flippi.ai
          
          # Test configuration
          echo "Testing nginx configuration..."
          nginx -t
          
          if [ $? -eq 0 ]; then
              echo "Reloading nginx..."
              nginx -s reload
              echo "✅ Nginx templates deployed successfully!"
              
              # Verify legal pages on blue
              echo ""
              echo "Verifying legal pages on blue.flippi.ai..."
              curl -s -o /dev/null -w "Privacy page: %{http_code}\n" http://localhost:8082/privacy || true
              curl -s -o /dev/null -w "Terms page: %{http_code}\n" http://localhost:8082/terms || true
          else
              echo "❌ Nginx configuration test failed!"
              # Restore backups
              echo "Restoring backups..."
              [ -f /etc/nginx/sites-available/blue.flippi.ai.backup-* ] && cp /etc/nginx/sites-available/blue.flippi.ai.backup-* /etc/nginx/sites-available/blue.flippi.ai
              [ -f /etc/nginx/sites-available/green.flippi.ai.backup-* ] && cp /etc/nginx/sites-available/green.flippi.ai.backup-* /etc/nginx/sites-available/green.flippi.ai
              [ -f /etc/nginx/sites-available/app.flippi.ai.backup-* ] && cp /etc/nginx/sites-available/app.flippi.ai.backup-* /etc/nginx/sites-available/app.flippi.ai
              exit 1
          fi
          
          # Cleanup
          rm -rf $TEMP_DIR