name: Deploy Development
on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to blue.flippi.ai
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 157.245.142.145
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/blue.flippi.ai
            git pull origin develop
            cd backend && npm install --production
            cd ../mobile-app && npm install && npx expo export --platform web --output-dir dist
            # Check what PM2 is actually serving
            pm2 describe dev-frontend | grep -E "script|args"
            # Stop and restart with correct path
            pm2 stop dev-frontend
            pm2 delete dev-frontend
            pm2 start npx --name "dev-frontend" -- serve -s /var/www/blue.flippi.ai/mobile-app/dist -l 8082
            pm2 restart dev-backend
            pm2 save