name: Deploy Staging to Green

on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: app.flippi.ai
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/green.flippi.ai
            git pull origin staging
            cd backend && npm install --production
            cd ../mobile-app && npm install
            EXPO_PUBLIC_API_URL="" npx expo build:web
            pm2 restart staging-backend
            pm2 restart staging-frontend
            sleep 5
            curl -f https://green.flippi.ai/health || exit 1
