name: Deploy Development
on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to blue.flippi.ai
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 157.245.142.145
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/blue.flippi.ai
            echo "=== [$(date)] Starting deployment ==="
            
            # Reset and pull latest code
            git reset --hard HEAD
            git clean -fd
            git fetch origin develop
            git reset --hard origin/develop
            echo "Latest commit: $(git log -1 --oneline)"
            
            # Install backend dependencies
            echo "=== [$(date)] Installing backend dependencies ==="
            cd backend && npm install --production || exit 1
            
            # Run database migrations
            echo "=== [$(date)] Running database migrations ==="
            export FEEDBACK_DB_PATH=/var/www/blue.flippi.ai/backend/flippi.db
            node scripts/run-growth-analytics-migration.js || echo "Migration already applied or failed"
            
            # Build frontend
            echo "=== [$(date)] Building frontend ==="
            cd ../mobile-app
            # Clean ALL caches to fix build issues
            rm -rf node_modules/.cache .expo dist web-build package-lock.json
            rm -rf /tmp/metro-* /tmp/haste-map-*
            # Clean install dependencies
            npm cache clean --force
            npm install || exit 1
            # Build with clean cache
            npx expo export --platform web --output-dir dist --clear || exit 1
            
            # Copy web assets
            cp web-styles.css dist/ || echo "Warning: Could not copy web-styles.css"
            
            # Deploy nginx configuration
            echo "=== [$(date)] Deploying nginx configuration ==="
            bash scripts/deploy-nginx-template.sh blue.flippi.ai || echo "Nginx deployment failed"
            
            # Restart services
            echo "=== [$(date)] Restarting services ==="
            pm2 restart dev-backend dev-frontend
            sleep 5
            
            # Verify deployment
            echo "=== [$(date)] Verifying deployment ==="
            curl -s http://localhost:3002/health || echo "Backend not responding"
            echo "Deployment complete"
