name: Deploy Develop to Blue

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to development
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: app.flippi.ai
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/blue.flippi.ai
            # Force clean state
            git reset --hard
            git clean -fd
            git pull origin develop
            # Backend
            cd backend && npm install --production
            # Frontend
            cd ../mobile-app 
            npm install
            # Use branded App if exists
            [ -f App-branded.js ] && cp App-branded.js App.js
            npx expo export --platform web
            # Restart
            pm2 restart dev-backend dev-frontend
            sleep 5
            curl -f https://blue.flippi.ai/health || exit 1
