name: Deploy Production

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Docker images
        run: |
          docker build -t thrifting-buddy/backend:v0.1.1 -f backend/Dockerfile ./backend
          docker build -t thrifting-buddy/frontend:v0.1.1 -f mobile-app/Dockerfile ./mobile-app
      
      - name: Save Docker images
        run: |
          docker save thrifting-buddy/backend:v0.1.1 thrifting-buddy/frontend:v0.1.1 | gzip > images.tar.gz
      
      - name: Deploy to production
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: app.flippi.ai
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Note: This requires SSH key setup and proper server access
            echo "This workflow requires SSH_PRIVATE_KEY secret to be configured"
