name: Deploy Production

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to app.flippi.ai
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: app.flippi.ai
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/app
            git fetch origin
            git checkout master
            git pull origin master
            docker-compose down
            docker-compose up -d --build
