name: Deploy Develop to Blue

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to development
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: app.flippi.ai
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/blue.flippi.ai
            git reset --hard origin/develop
            git clean -fd
            cd backend && npm install --production
            cd ../mobile-app && npm install
            npx expo export --platform web
            pm2 restart dev-backend
            pm2 restart dev-frontend
            sleep 5
            curl -f https://blue.flippi.ai/health || exit 1
