name: Deploy Staging to Green

on:
  push:
    branches: [staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to green.flippi.ai
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: green.flippi.ai
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/app
            git fetch origin
            git checkout staging
            git pull origin staging
            docker-compose down
            docker-compose up -d --build
