name: Direct Nginx Fix
on:
  workflow_dispatch:
  push:
    branches: [develop]
    paths:
      - '.github/workflows/direct-nginx-fix.yml'

jobs:
  fix-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Apply nginx fix directly
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 157.245.142.145
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "=== Direct nginx fix for growth routes ==="
            
            # First, let's see what's actually happening
            echo "Current nginx sites-enabled:"
            ls -la /etc/nginx/sites-enabled/
            
            echo ""
            echo "Checking main nginx config includes:"
            grep -n "include.*sites-enabled" /etc/nginx/nginx.conf
            
            # The actual fix - add growth routes to whatever config is active
            CONFIG_FILE=$(ls /etc/nginx/sites-enabled/blue.flippi.ai 2>/dev/null || ls /etc/nginx/sites-enabled/flippi.conf 2>/dev/null || echo "")
            
            if [ -z "$CONFIG_FILE" ]; then
                echo "ERROR: No config file found!"
                exit 1
            fi
            
            echo "Working with config: $CONFIG_FILE"
            REAL_FILE=$(readlink -f "$CONFIG_FILE")
            echo "Real file: $REAL_FILE"
            
            # Check if growth routes exist
            if ! sudo grep -q "location.*growth" "$REAL_FILE"; then
                echo "Adding growth routes..."
                
                # Backup
                sudo cp "$REAL_FILE" "${REAL_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
                
                # Find where to insert (before the catch-all location /)
                LINE_NUM=$(sudo grep -n "location / {" "$REAL_FILE" | head -1 | cut -d: -f1)
                
                if [ -n "$LINE_NUM" ]; then
                    # Insert growth routes before the catch-all
                    sudo sed -i "${LINE_NUM}i\\
    # Growth backend endpoints\\
    location ^~ /growth {\\
        proxy_pass http://127.0.0.1:3002;\\
        proxy_http_version 1.1;\\
        proxy_set_header Host \$host;\\
        proxy_set_header X-Real-IP \$remote_addr;\\
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;\\
        proxy_set_header X-Forwarded-Proto \$scheme;\\
    }\\
" "$REAL_FILE"
                else
                    echo "ERROR: Could not find catch-all location"
                    exit 1
                fi
            else
                echo "Growth routes already exist"
            fi
            
            # Test and reload
            echo ""
            echo "Testing nginx..."
            if sudo nginx -t; then
                sudo systemctl reload nginx
                echo "✅ Nginx reloaded"
            else
                echo "❌ Nginx test failed"
                exit 1
            fi
            
            # Final test
            sleep 2
            echo ""
            echo "Testing /growth/questions..."
            RESPONSE=$(curl -sS https://blue.flippi.ai/growth/questions 2>&1 | head -100)
            if echo "$RESPONSE" | grep -q "Questions Found"; then
                echo "✅ SUCCESS: Growth routes are working!"
                echo "$RESPONSE" | grep -A2 "Questions Found"
            else
                echo "⚠️  Still not working. Response:"
                echo "$RESPONSE" | head -20
                
                echo ""
                echo "Checking backend directly:"
                curl -s http://localhost:3002/growth/questions | head -10
            fi