name: Fix Production NOW
on:
  workflow_dispatch:
  push:
    branches: [develop]
    paths:
      - '.github/workflows/fix-prod-now.yml'

jobs:
  fix-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Fix production immediately
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 157.245.142.145
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "=== FIXING PRODUCTION NOW ==="
            
            # Check what's wrong
            echo "Current production config:"
            ls -la /etc/nginx/sites-enabled/ | grep app
            
            # Check if production directory exists
            echo "Production directory:"
            ls -la /var/www/ | grep app
            
            # Find any production config
            PROD_CONFIG=""
            if [ -f /var/www/app.flippi.ai/infra-nginx/sites/flippi-prod.conf ]; then
                PROD_CONFIG="/var/www/app.flippi.ai/infra-nginx/sites/flippi-prod.conf"
            elif [ -f /var/www/flippi.ai/infra-nginx/sites/flippi-prod.conf ]; then
                PROD_CONFIG="/var/www/flippi.ai/infra-nginx/sites/flippi-prod.conf"
            elif [ -f /etc/nginx/sites-available/app.flippi.ai.backup* ]; then
                PROD_CONFIG=$(ls -t /etc/nginx/sites-available/app.flippi.ai.backup* | head -1)
            fi
            
            if [ -n "$PROD_CONFIG" ]; then
                echo "Using config: $PROD_CONFIG"
                sudo cp "$PROD_CONFIG" /etc/nginx/sites-available/app.flippi.ai
            else
                echo "Creating minimal production config..."
                sudo cat > /etc/nginx/sites-available/app.flippi.ai << 'EOF'
            server {
                listen 80;
                server_name app.flippi.ai;
                return 301 https://$server_name$request_uri;
            }
            
            server {
                listen 443 ssl;
                server_name app.flippi.ai;
                
                ssl_certificate /etc/letsencrypt/live/app.flippi.ai/fullchain.pem;
                ssl_certificate_key /etc/letsencrypt/live/app.flippi.ai/privkey.pem;
                
                root /var/www/app.flippi.ai/mobile-app/dist;
                
                location / {
                    try_files $uri /index.html;
                }
                
                location /api {
                    proxy_pass http://localhost:3000;
                    proxy_http_version 1.1;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                }
                
                location /auth {
                    proxy_pass http://localhost:3000;
                    proxy_http_version 1.1;
                    proxy_set_header Host $host;
                }
            }
            EOF
            fi
            
            # Ensure symlink
            sudo rm -f /etc/nginx/sites-enabled/app.flippi.ai
            sudo ln -sf /etc/nginx/sites-available/app.flippi.ai /etc/nginx/sites-enabled/app.flippi.ai
            
            # Test and reload
            sudo nginx -t && sudo systemctl reload nginx
            
            # Verify
            echo ""
            echo "Testing production:"
            curl -I https://app.flippi.ai 2>&1 | head -5