name: Fix Blue CSS MIME Type
on:
  workflow_dispatch:
  push:
    branches: [develop]
    paths:
      - '.github/workflows/fix-blue-css.yml'

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Fix nginx CSS serving
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 157.245.142.145
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Add static file handling before SPA fallback
            cat > /tmp/static-files.conf << 'EOF'
            location ~* \.(css|js|mjs|map|png|jpg|jpeg|gif|svg|ico|woff2?)$ {
              root /var/www/blue.flippi.ai/mobile-app/dist;
              try_files $uri =404;
              add_header Cache-Control "public, max-age=31536000, immutable";
            }
            EOF
            
            # Insert before main location block
            sed -i '/location \/ {/i \    include /tmp/static-files.conf;' /etc/nginx/sites-available/blue.flippi.ai
            
            # Test and reload
            nginx -t && systemctl reload nginx
            
            # Verify fix
            curl -I https://blue.flippi.ai/web-styles.css | grep -i 'Content-Type'