name: Fix Nginx Only - Direct
on:
  workflow_dispatch:
  push:
    branches: [develop]
    paths:
      - '.github/workflows/fix-nginx-only.yml'

jobs:
  fix-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Fix nginx growth routes
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 157.245.142.145
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "=== Deploying nginx configuration from infra-nginx ==="
            cd /var/www/blue.flippi.ai
            
            # Pull latest code to get infra-nginx updates
            echo "Pulling latest code..."
            git fetch origin develop
            git reset --hard origin/develop
            
            # Use the infra-nginx deployment script
            echo "Running infra-nginx deployment..."
            cd infra-nginx
            if [ -f "deploy-nginx.sh" ]; then
                sudo bash deploy-nginx.sh blue
            else
                # Fallback: manually copy the config
                echo "Deploy script not found, copying config manually..."
                if [ -f "sites/flippi-blue.conf" ]; then
                    sudo cp sites/flippi-blue.conf /etc/nginx/sites-available/blue.flippi.ai
                    sudo nginx -t && sudo systemctl reload nginx
                else
                    echo "ERROR: Config file not found at sites/flippi-blue.conf"
                    exit 1
                fi
            fi
            
            # Verify deployment
            echo ""
            echo "Verifying nginx configuration..."
            sudo nginx -T | grep -A5 "server_name blue.flippi.ai" | head -20
            
            echo ""
            echo "Testing /growth/questions route..."
            RESPONSE=$(curl -s https://blue.flippi.ai/growth/questions | head -100)
            if echo "$RESPONSE" | grep -q "Questions Found"; then
                echo "✅ SUCCESS: Growth routes are working!"
            else
                echo "⚠️  Still showing React app. Backend response:"
                curl -s http://localhost:3002/growth/questions | head -20
            fi
            
            echo ""
            echo "=== Complete ==="