name: Force Nginx Fix
on:
  workflow_dispatch:
  push:
    branches: [develop]
    paths:
      - '.github/workflows/force-nginx-fix.yml'

jobs:
  fix-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Force fix nginx routes
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 157.245.142.145
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "=== Force Nginx Fix ==="
            
            # Create a working nginx config with growth routes
            cat > /tmp/nginx-growth-fix.conf << 'EOF'
    # Growth backend endpoints
    location ^~ /growth {
        proxy_pass http://127.0.0.1:3002;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
            EOF
            
            # Find the actual config file
            NGINX_CONFIG=""
            if [ -L /etc/nginx/sites-enabled/blue.flippi.ai ]; then
                NGINX_CONFIG=$(readlink -f /etc/nginx/sites-enabled/blue.flippi.ai)
            elif [ -L /etc/nginx/sites-enabled/flippi.conf ]; then
                NGINX_CONFIG=$(readlink -f /etc/nginx/sites-enabled/flippi.conf)
            elif [ -f /etc/nginx/sites-available/blue.flippi.ai ]; then
                NGINX_CONFIG="/etc/nginx/sites-available/blue.flippi.ai"
            fi
            
            if [ -z "$NGINX_CONFIG" ]; then
                echo "ERROR: Could not find nginx config"
                exit 1
            fi
            
            echo "Working with: $NGINX_CONFIG"
            
            # Backup
            sudo cp "$NGINX_CONFIG" "${NGINX_CONFIG}.backup.force.$(date +%Y%m%d_%H%M%S)"
            
            # Check if growth routes exist
            if ! grep -q "location.*growth" "$NGINX_CONFIG"; then
                echo "Adding growth routes..."
                
                # Create temp file
                TEMP_FILE="/tmp/nginx_config_$$.tmp"
                sudo cp "$NGINX_CONFIG" "$TEMP_FILE"
                
                # Find line number after legal routes (terms, privacy, etc)
                AFTER_LINE=$(grep -n "location = /contact {" "$TEMP_FILE" | tail -1 | cut -d: -f1)
                if [ -n "$AFTER_LINE" ]; then
                    # Count lines to skip (usually 5-6 lines for the location block)
                    SKIP_LINES=6
                    INSERT_LINE=$((AFTER_LINE + SKIP_LINES))
                    
                    # Insert the growth routes
                    sudo sed -i "${INSERT_LINE}r /tmp/nginx-growth-fix.conf" "$TEMP_FILE"
                    
                    # Copy back
                    sudo cp "$TEMP_FILE" "$NGINX_CONFIG"
                    rm -f "$TEMP_FILE"
                    
                    echo "Growth routes added"
                else
                    echo "Could not find insertion point"
                fi
            else
                echo "Growth routes already present"
            fi
            
            # Remove any duplicate location blocks
            echo "Checking for duplicates..."
            sudo awk '!/^[[:space:]]*$/ || !p; {p=/^[[:space:]]*$/}' "$NGINX_CONFIG" > /tmp/cleaned.conf
            sudo cp /tmp/cleaned.conf "$NGINX_CONFIG"
            
            # Test and reload
            echo "Testing nginx..."
            if sudo nginx -t; then
                sudo systemctl reload nginx
                echo "✅ Nginx reloaded"
            else
                echo "❌ Config test failed"
                cat "$NGINX_CONFIG" | grep -n "growth" | head -10
                exit 1
            fi
            
            # Test the route
            sleep 3
            echo ""
            echo "Testing /growth/questions..."
            TITLE=$(curl -s https://blue.flippi.ai/growth/questions | grep -o "<title>.*</title>" | head -1)
            echo "Page title: $TITLE"
            
            if [[ "$TITLE" == *"Questions Found"* ]]; then
                echo "✅ SUCCESS! Growth routes are working!"
            else
                echo "❌ Still not working"
                echo ""
                echo "Nginx config growth section:"
                grep -A5 -B2 "growth" "$NGINX_CONFIG" | head -20
            fi