name: Force CSS Fix
on:
  workflow_dispatch:
  push:
    branches: [develop]
    paths:
      - '.github/workflows/force-css-fix.yml'

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Force nginx to serve CSS correctly
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 157.245.142.145
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Backup current config
            cp /etc/nginx/sites-available/blue.flippi.ai /etc/nginx/sites-available/blue.flippi.ai.bak
            
            # Add CSS location BEFORE the catch-all
            sed -i '/location \/ {/i \
                location = /web-styles.css {\
                    root /var/www/blue.flippi.ai/mobile-app/dist;\
                    try_files /_expo/static/css/web-styles-639f7651a30e118ac73011fab7c7040a.css =404;\
                    add_header Content-Type text/css;\
                }\
            ' /etc/nginx/sites-available/blue.flippi.ai
            
            # Reload nginx
            nginx -s reload
            
            # Test immediately
            sleep 2
            curl -I https://blue.flippi.ai/web-styles.css