name: Full Nginx Recovery
on:
  workflow_dispatch:
  push:
    branches: [develop]
    paths:
      - '.github/workflows/full-nginx-recovery.yml'

jobs:
  full-recover:
    runs-on: ubuntu-latest
    steps:
      - name: Full nginx recovery
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 157.245.142.145
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "=== FULL NGINX RECOVERY ==="
            
            # 1. Stop nginx completely
            echo "Stopping nginx..."
            sudo systemctl stop nginx || true
            sudo killall nginx || true
            
            # 2. Check for SSL cert issues
            echo ""
            echo "Checking SSL certificates..."
            ls -la /etc/letsencrypt/live/blue.flippi.ai/ || echo "No SSL certs found"
            
            # 3. Use the simplest working config
            echo ""
            echo "Creating minimal working config..."
            sudo cat > /etc/nginx/sites-available/blue.flippi.ai << 'EOF'
            server {
                listen 80;
                server_name blue.flippi.ai;
                
                location / {
                    return 301 https://$server_name$request_uri;
                }
            }
            
            server {
                listen 443 ssl;
                server_name blue.flippi.ai;
                
                ssl_certificate /etc/letsencrypt/live/blue.flippi.ai/fullchain.pem;
                ssl_certificate_key /etc/letsencrypt/live/blue.flippi.ai/privkey.pem;
                
                root /var/www/blue.flippi.ai/mobile-app/dist;
                index index.html;
                
                # Legal pages first
                location = /terms {
                    proxy_pass http://localhost:3002;
                }
                
                location = /privacy {
                    proxy_pass http://localhost:3002;
                }
                
                location = /mission {
                    proxy_pass http://localhost:3002;
                }
                
                location = /contact {
                    proxy_pass http://localhost:3002;
                }
                
                # Growth routes - MUST BE HERE
                location /growth {
                    proxy_pass http://localhost:3002;
                }
                
                # API routes
                location /api {
                    proxy_pass http://localhost:3002;
                }
                
                # Auth routes
                location /auth {
                    proxy_pass http://localhost:3002;
                }
                
                # React app
                location / {
                    try_files $uri /index.html;
                }
            }
            EOF
            
            # 4. Ensure symlink exists
            echo ""
            echo "Creating symlink..."
            sudo rm -f /etc/nginx/sites-enabled/blue.flippi.ai
            sudo ln -s /etc/nginx/sites-available/blue.flippi.ai /etc/nginx/sites-enabled/blue.flippi.ai
            
            # 5. Remove any conflicting configs
            echo ""
            echo "Removing conflicts..."
            sudo rm -f /etc/nginx/sites-enabled/default
            sudo rm -f /etc/nginx/sites-enabled/flippi.conf
            
            # 6. Test configuration
            echo ""
            echo "Testing configuration..."
            sudo nginx -t
            
            # 7. Start nginx
            echo ""
            echo "Starting nginx..."
            sudo systemctl start nginx
            
            # 8. Check status
            echo ""
            echo "Nginx status:"
            sudo systemctl status nginx --no-pager | head -10
            
            # 9. Test the site
            echo ""
            echo "Testing site..."
            sleep 3
            curl -I https://blue.flippi.ai 2>&1 | head -5
            
            # 10. Test growth route
            echo ""
            echo "Testing growth route..."
            curl -s https://blue.flippi.ai/growth/questions | grep -o "<title>.*</title>" | head -1