name: Mobile App CI

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'mobile-app/**'
      - '.github/workflows/mobile-ci.yml'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'mobile-app/**'
      - '.github/workflows/mobile-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: mobile-app/package-lock.json
    
    - name: Install dependencies
      working-directory: ./mobile-app
      run: npm ci
    
    - name: Run linter
      working-directory: ./mobile-app
      run: npm run lint || true  # Don't fail on lint errors for now
    
    - name: Check TypeScript (if applicable)
      working-directory: ./mobile-app
      run: npx tsc --noEmit || true
      continue-on-error: true

  expo-doctor:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: mobile-app/package-lock.json
    
    - name: Setup Expo
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
    
    - name: Install dependencies
      working-directory: ./mobile-app
      run: npm ci
    
    - name: Run Expo Doctor
      working-directory: ./mobile-app
      run: npx expo-doctor || true

  build-android:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: mobile-app/package-lock.json
    
    - name: Setup Expo
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
    
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Install dependencies
      working-directory: ./mobile-app
      run: npm ci
    
    - name: Prebuild Android
      working-directory: ./mobile-app
      run: npx expo prebuild --platform android --no-install
      continue-on-error: true

  build-ios:
    runs-on: macos-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: mobile-app/package-lock.json
    
    - name: Setup Expo
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
    
    - name: Install dependencies
      working-directory: ./mobile-app
      run: npm ci
    
    - name: Prebuild iOS
      working-directory: ./mobile-app
      run: npx expo prebuild --platform ios --no-install
      continue-on-error: true