name: Quick CSS Fix
on:
  workflow_dispatch:
  push:
    branches: [develop]
    paths:
      - '.github/workflows/quick-css-fix.yml'

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Direct CSS symlink fix
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 157.245.142.145
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/blue.flippi.ai/mobile-app/dist
            # Create symlink from web-styles.css to actual CSS file
            CSS_FILE=$(find _expo/static/css -name "web-styles-*.css" | head -1)
            ln -sf $CSS_FILE web-styles.css
            ls -la web-styles.css
            # Test immediately
            curl -I https://blue.flippi.ai/web-styles.css | grep -i content-type