name: RESTORE PRODUCTION IMMEDIATELY
on:
  workflow_dispatch:
  push:
    branches: [develop]
    paths:
      - '.github/workflows/restore-prod-immediately.yml'

jobs:
  restore-prod:
    runs-on: ubuntu-latest
    steps:
      - name: RESTORE PRODUCTION NOW
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 157.245.142.145
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "=== RESTORING PRODUCTION ==="
            
            # Find the most recent working backup
            BACKUP=$(ls -t /etc/nginx/sites-available/app.flippi.ai.backup* 2>/dev/null | head -1)
            if [ -n "$BACKUP" ]; then
                echo "Restoring from backup: $BACKUP"
                sudo cp "$BACKUP" /etc/nginx/sites-available/app.flippi.ai
            else
                # Create a known working config
                sudo cat > /etc/nginx/sites-available/app.flippi.ai << 'EOF'
            server {
                listen 80;
                server_name app.flippi.ai;
                return 301 https://$server_name$request_uri;
            }
            
            server {
                listen 443 ssl;
                server_name app.flippi.ai;
                
                ssl_certificate /etc/letsencrypt/live/app.flippi.ai/fullchain.pem;
                ssl_certificate_key /etc/letsencrypt/live/app.flippi.ai/privkey.pem;
                
                root /var/www/flippi.ai/mobile-app/web-build;
                
                location /api {
                    proxy_pass http://localhost:3000;
                    proxy_http_version 1.1;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }
                
                location /auth {
                    proxy_pass http://localhost:3000;
                    proxy_http_version 1.1;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }
                
                location / {
                    try_files $uri /index.html;
                }
            }
            EOF
            fi
            
            # Force the symlink
            sudo rm -f /etc/nginx/sites-enabled/app.flippi.ai
            sudo ln -sf /etc/nginx/sites-available/app.flippi.ai /etc/nginx/sites-enabled/app.flippi.ai
            
            # Remove any conflicting configs
            sudo rm -f /etc/nginx/sites-enabled/default
            sudo rm -f /etc/nginx/sites-enabled/flippi.conf
            
            # Test and force reload
            sudo nginx -t
            sudo systemctl reload nginx
            
            # Make sure production PM2 is running
            pm2 start prod-backend || true
            pm2 start prod-frontend || true
            
            echo "PRODUCTION SHOULD BE RESTORED"