name: Simple Nginx Fix
on:
  workflow_dispatch:
  push:
    branches: [develop]
    paths:
      - '.github/workflows/simple-nginx-fix.yml'

jobs:
  fix-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Fix nginx growth routes
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 157.245.142.145
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Find and fix the actual nginx config being used
            echo "=== Simple Nginx Fix ==="
            
            # Method 1: Check what nginx is actually using
            echo "Active nginx server blocks:"
            sudo nginx -T 2>/dev/null | grep -E "server_name.*blue.flippi.ai" -B2 -A20 | grep -E "(server_name|location|proxy_pass)" | head -30
            
            # Method 2: Force add to all possible configs
            for config in /etc/nginx/sites-available/blue.flippi.ai /etc/nginx/sites-available/flippi.conf /etc/nginx/sites-enabled/blue.flippi.ai /etc/nginx/sites-enabled/flippi.conf; do
                if [ -f "$config" ]; then
                    echo ""
                    echo "Checking $config..."
                    if grep -q "server_name.*blue.flippi.ai" "$config" 2>/dev/null; then
                        echo "Found blue.flippi.ai in $config"
                        
                        # Add growth routes if missing
                        if ! grep -q "location.*growth" "$config"; then
                            echo "Adding growth routes to $config"
                            sudo sed -i '/location = \/terms {/a\
            \
                location ^~ /growth {\
                    proxy_pass http://127.0.0.1:3002;\
                    proxy_http_version 1.1;\
                    proxy_set_header Host $host;\
                    proxy_set_header X-Real-IP $remote_addr;\
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\
                    proxy_set_header X-Forwarded-Proto $scheme;\
                }\
            ' "$config" || echo "Failed to add with sed"
                        fi
                    fi
                fi
            done
            
            # Test and reload
            sudo nginx -t && sudo systemctl reload nginx
            
            # Verify
            echo ""
            echo "Testing..."
            curl -s https://blue.flippi.ai/growth/questions | grep -o "<title>.*</title>" | head -1